services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - disknet
  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate
      -path /migrations 
      -database postgres://postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      up
    networks:
      - disknet
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${API_GATEWAY_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet
  calender-service:
    build: ./services/calender-service
    container_name: calender-service
    env_file:
      - ./config/docker.env
    ports:
      - "${CALENDER_SERVICE_PORT}:${CALENDER_SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${CALENDER_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

volumes:
  postgres_data:

networks:
  disknet:
    driver: bridge