services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - disknet
  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate
      -path /migrations 
      -database postgres://postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      up
    networks:
      - disknet
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    env_file:
      - ./config/docker.env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${API_GATEWAY_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet
  calender-service:
    build: ./services/calender-service
    container_name: calender-service
    env_file:
      - ./config/docker.env
    ports:
      - "${CALENDER_SERVICE_PORT}:${CALENDER_SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${CALENDER_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - ./config/docker.env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${AUTH_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet
  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - ./config/docker.env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-qO-"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet
  
  camp-service:
    build: ./services/camp-service
    container_name: camp-service
    env_file:
      - ./config/docker.env
    ports:
      - "${CAMP_SERVICE_PORT}:${CAMP_SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

  file-service:
    build: ./services/file-service
    container_name: file-service
    env_file:
      - ./config/docker.env
    ports:
      - "${FILE_SERVICE_PORT}:${FILE_SERVICE_PORT}"
    volumes:
      - "family-steam:/data"
    healthcheck:
      test: ["CMD", "wget", "-qO-"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - disknet

volumes:
  postgres_data:
  family-steam:

networks:
  disknet:
    driver: bridge