ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS user_id        TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS username       TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar         TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'cash';
