// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/proto/user-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsUserTheAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTheAdminRequest) Reset() {
	*x = IsUserTheAdminRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTheAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTheAdminRequest) ProtoMessage() {}

func (x *IsUserTheAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTheAdminRequest.ProtoReflect.Descriptor instead.
func (*IsUserTheAdminRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *IsUserTheAdminRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type IsUserTheAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTheAdminResponse) Reset() {
	*x = IsUserTheAdminResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTheAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTheAdminResponse) ProtoMessage() {}

func (x *IsUserTheAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTheAdminResponse.ProtoReflect.Descriptor instead.
func (*IsUserTheAdminResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *IsUserTheAdminResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_proto_user_service_proto protoreflect.FileDescriptor

const file_internal_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/user-service.proto\x12\fuser_service\"/\n" +
	"\x15IsUserTheAdminRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"(\n" +
	"\x16IsUserTheAdminResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2j\n" +
	"\vUserService\x12[\n" +
	"\x0eIsUserTheAdmin\x12#.user_service.IsUserTheAdminRequest\x1a$.user_service.IsUserTheAdminResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_internal_proto_user_service_proto_rawDescOnce sync.Once
	file_internal_proto_user_service_proto_rawDescData []byte
)

func file_internal_proto_user_service_proto_rawDescGZIP() []byte {
	file_internal_proto_user_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)))
	})
	return file_internal_proto_user_service_proto_rawDescData
}

var file_internal_proto_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_user_service_proto_goTypes = []any{
	(*IsUserTheAdminRequest)(nil),  // 0: user_service.IsUserTheAdminRequest
	(*IsUserTheAdminResponse)(nil), // 1: user_service.IsUserTheAdminResponse
}
var file_internal_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user_service.UserService.IsUserTheAdmin:input_type -> user_service.IsUserTheAdminRequest
	1, // 1: user_service.UserService.IsUserTheAdmin:output_type -> user_service.IsUserTheAdminResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_user_service_proto_init() }
func file_internal_proto_user_service_proto_init() {
	if File_internal_proto_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_user_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_user_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_user_service_proto_msgTypes,
	}.Build()
	File_internal_proto_user_service_proto = out.File
	file_internal_proto_user_service_proto_goTypes = nil
	file_internal_proto_user_service_proto_depIdxs = nil
}
