// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/proto/user-service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserRequest) Reset() {
	*x = SaveUserRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserRequest) ProtoMessage() {}

func (x *SaveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserRequest.ProtoReflect.Descriptor instead.
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SaveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserResponse) Reset() {
	*x = SaveUserResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserResponse) ProtoMessage() {}

func (x *SaveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserResponse.ProtoReflect.Descriptor instead.
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUsersIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersIDRequest) Reset() {
	*x = GetUsersIDRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersIDRequest) ProtoMessage() {}

func (x *GetUsersIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersIDRequest.ProtoReflect.Descriptor instead.
func (*GetUsersIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersIDRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetUsersIDRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUsersIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersIDResponse) Reset() {
	*x = GetUsersIDResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersIDResponse) ProtoMessage() {}

func (x *GetUsersIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersIDResponse.ProtoReflect.Descriptor instead.
func (*GetUsersIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IsUserTheAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTheAdminRequest) Reset() {
	*x = IsUserTheAdminRequest{}
	mi := &file_internal_proto_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTheAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTheAdminRequest) ProtoMessage() {}

func (x *IsUserTheAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTheAdminRequest.ProtoReflect.Descriptor instead.
func (*IsUserTheAdminRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *IsUserTheAdminRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type IsUserTheAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserTheAdminResponse) Reset() {
	*x = IsUserTheAdminResponse{}
	mi := &file_internal_proto_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserTheAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserTheAdminResponse) ProtoMessage() {}

func (x *IsUserTheAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserTheAdminResponse.ProtoReflect.Descriptor instead.
func (*IsUserTheAdminResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *IsUserTheAdminResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_proto_user_service_proto protoreflect.FileDescriptor

const file_internal_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/user-service.proto\x12\fuser_service\"I\n" +
	"\x0fSaveUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\x10SaveUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x11GetUsersIDRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"$\n" +
	"\x12GetUsersIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x15IsUserTheAdminRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"(\n" +
	"\x16IsUserTheAdminResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x8b\x02\n" +
	"\vUserService\x12I\n" +
	"\bSaveUser\x12\x1d.user_service.SaveUserRequest\x1a\x1e.user_service.SaveUserResponse\x12T\n" +
	"\x0fGetUserPassword\x12\x1f.user_service.GetUsersIDRequest\x1a .user_service.GetUsersIDResponse\x12[\n" +
	"\x0eIsUserTheAdmin\x12#.user_service.IsUserTheAdminRequest\x1a$.user_service.IsUserTheAdminResponseB\x17Z\x15/internal/proto;protob\x06proto3"

var (
	file_internal_proto_user_service_proto_rawDescOnce sync.Once
	file_internal_proto_user_service_proto_rawDescData []byte
)

func file_internal_proto_user_service_proto_rawDescGZIP() []byte {
	file_internal_proto_user_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)))
	})
	return file_internal_proto_user_service_proto_rawDescData
}

var file_internal_proto_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_user_service_proto_goTypes = []any{
	(*SaveUserRequest)(nil),        // 0: user_service.SaveUserRequest
	(*SaveUserResponse)(nil),       // 1: user_service.SaveUserResponse
	(*GetUsersIDRequest)(nil),      // 2: user_service.GetUsersIDRequest
	(*GetUsersIDResponse)(nil),     // 3: user_service.GetUsersIDResponse
	(*IsUserTheAdminRequest)(nil),  // 4: user_service.IsUserTheAdminRequest
	(*IsUserTheAdminResponse)(nil), // 5: user_service.IsUserTheAdminResponse
}
var file_internal_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user_service.UserService.SaveUser:input_type -> user_service.SaveUserRequest
	2, // 1: user_service.UserService.GetUserPassword:input_type -> user_service.GetUsersIDRequest
	4, // 2: user_service.UserService.IsUserTheAdmin:input_type -> user_service.IsUserTheAdminRequest
	1, // 3: user_service.UserService.SaveUser:output_type -> user_service.SaveUserResponse
	3, // 4: user_service.UserService.GetUserPassword:output_type -> user_service.GetUsersIDResponse
	5, // 5: user_service.UserService.IsUserTheAdmin:output_type -> user_service.IsUserTheAdminResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_user_service_proto_init() }
func file_internal_proto_user_service_proto_init() {
	if File_internal_proto_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_user_service_proto_rawDesc), len(file_internal_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_user_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_user_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_user_service_proto_msgTypes,
	}.Build()
	File_internal_proto_user_service_proto = out.File
	file_internal_proto_user_service_proto_goTypes = nil
	file_internal_proto_user_service_proto_depIdxs = nil
}
